name: test
on:
  push:
    branches: ['**']
    tags-ignore: ['v*']
  pull_request:
    branches: ['**']
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: check code
        run: make check
      - name: run tests
        run: make test
  msrv:
    name: msrv
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: check minimum supported rust version
        run: make msrv
